### ISSUE TITLE
nats-box changes default URL to be NGS

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-box#10]
Change default URL to be `localhost:4222` unless otherwise defined.

The default use case is:

```
docker run --rm --network host -it -v /tmp/configs:/configs synadia/nats-server:latest
```
```
docker run --rm --network host -it  synadia/nats-box:latest
nats-pub foo bar
```

With network host, this works right out of the box without any typing. Instead it gets (correctly) an error from NGS.

**Comment by variadico** [comment]
Makes sense. Defaulting to NGS is surprising.

**Comment by wallyqs** [comment]
sounds good to me as well

**Comment by variadico** [comment]
Fixed by https://github.com/nats-io/nats-box/pull/12#pullrequestreview-515913177
