### ISSUE TITLE
Authorization Violation on stream ls on a leaf node

### ISSUE THREAD

**Issue by vlad-gaman** [nats-io/nats-box#33]
Hello, I have this as a docker image and I am trying to connect with the provided nats cli to see what streams it has, however I get the following error...

~ # nats stream ls
nats: error: setup failed: nats: Authorization Violation

I do have some accounts setup and I did setup the server with one of the accounts

**Comment by caleblloyd** [comment]
Closing due to age; please open a new issue if you are still seeing this
