### ISSUE TITLE
replace Dockerfile ENTRYPOINT with CMD

### ISSUE THREAD

**Issue by steevehook** [nats-io/nats-box#34]
## Issue

Tried referring to the `nats` binary without SHELL-ing into the box and it gave me the following error.
`docker run --rm natsio/nats-box:latest /usr/local/bin/nats stream add stream_name`

## Solution

My recommendation is to replace `ENTRYPOINT` with `CMD` to allow external commands to overwrite it

<img width="717" alt="image" src="https://user-images.githubusercontent.com/16312516/179479861-41478565-80d2-4172-9408-59a5ae26f85b.png">

**Comment by caleblloyd** [comment]
Fixed in #47
