### ISSUE TITLE
fix security vulnerabilities

### ISSUE THREAD

**Issue by jaredmcqueen** [nats-io/nats-box#46]
The security team at my work use artifacthub to assess security vulnerabilities.  They noticed some failing scores on nats-box.  Link here:
https://artifacthub.io/packages/helm/nats/nats

(click open full report)
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/3491953/212118387-c6e2c225-9ab7-4501-bd75-c871b1305547.png">

It seems like the fixes are to use a newer version of alpine, and use a newer JWT library.
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/3491953/212118959-a15c590b-aaa1-4171-9555-a565a8149b0b.png">

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/3491953/212119086-979ee9b5-103a-41e2-afd1-68d5bfd98de7.png">

**Comment by wallyqs** [comment]
Thanks for raising the issue, will do an update soon.
