### ISSUE TITLE
Cannot override NATS_URL environment variable when nats-box is installed in k8s

### ISSUE THREAD

**Issue by balamuru** [nats-io/nats-box#7]
When nats-box is installed in a kubernetes cluster either via helm or using a basic yaml spec, the default NATS_URL environment variable is generated

```
    env:
    - name: NATS_URL
      value: nats
```

As a result, the following are observed
* It is not possible to over-ride the the value of NATS_URL when using nats-box via the -s option eg. ```nats-box -s nats://some/other/server topic.test hello``` will still publish to ```nats```
* if the NATS_URL is removed from the yaml spec, it is possible to use the -s option as expected
* the NATS_URL should at least be namespace scoped  or even be removed

Slack discussion captured at https://natsio.slack.com/archives/C069GSYFP/p1593703420250700

@wallyqs  @ripienaar  were involved in the discussion

**Comment by balamuru** [comment]
Root cause :
BTW, .... looking at https://github.com/nats-io/nats-box/blob/master/main.go#L85 , ... if NATS_URL is spec'd in the environment, .. it ignores the -s option ... that is the root cause of the nats-box behavior i observed last week . Will add to the github issue 

	us := *urls ================> from command line args
	if v := os.Getenv("NATS_URL"); v != "" { =============> from env
		us = v
	}

**Comment by ripienaar** [comment]
This should be resolved in later versions since we're using the `nats` CLI.
